### ISSUE TITLE
Interface throws error when attempting to make XML a second time

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/BelleJS#7]
```
Failed to locate branchRates element in rateStatistic
```

**Comment by GopiGugan** [comment]
I think the the issue here is because "If the given child is a reference to an existing node in the document, `appendChild()` moves it from its current position to the new position" (https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild). So we need to use `cloneNode()` when we want to reuse an element (e.g. `dbr` in `updateBranchRates()`)
